<table class="wide">
<tr>
<td>Facebook Page Address </td><td>: <input class="wide float-right" type="text" name="facebook" required="required" value="<?php echo get_footer_data('facebook');?>
"/></td></tr>
<tr><td>Google Plus Address </td><td>: <input class="wide float-right" type="text" name="g-plus" required="required" value="<?php echo get_footer_data('g-plus');?>
"/></td></tr>
<tr><td>Twitter Account Address </td><td>: <input class="wide float-right" type="text" name="twitter" required="required" value="<?php echo get_footer_data('twitter');?>
"/></td></tr>
<tr><td>Telephone Number</td><td>: <input class="wide float-right" type="text" name="tel" value="<?php echo get_footer_data('tel');?>"/></td></tr>
<tr><td>Fax Number</td><td>: <input class="wide float-right" type="text" name="fax" value="<?php echo get_footer_data('fax');?>"/></td></tr>
<tr><td>E-mail Address </td><td>: <input class="wide float-right" type="email" name="twitter" required="required" value="<?php echo get_footer_data('contact');?>
"/></td></tr>
<tr><td colspan="2" class="align-right"><input type="submit" value="Update"/></td></tr>
</table>