	<div class="small-box bg-aqua">
        <div class="inner">
            <h3>150</h3>
            <p>Orders</p>
        </div>
        <img src="images/order.png" alt="" class="icon"/> 	
        <a href="#" class="small-box-footer">More info -></a>
	</div>
    <div class="small-box bg-green">
        <div class="inner">
            <h3>150</h3>
            <p>Products</p>
        </div>
        <img src="images/product.png" alt="" class="icon"/> 	
        <a href="#" class="small-box-footer">More info -></a>
	</div>
    <div class="small-box bg-maroon">
        <div class="inner">
            <h3>150</h3>
            <p>Customers</p>
        </div>
        <img src="images/user.png" alt="" class="icon"/> 	
        <a href="#" class="small-box-footer">More info -></a>
	</div>
    <div class="small-box bg-blue">
        <div class="inner">
            <h3>150</h3>
            <p>Sales</p>
        </div>
        <img src="images/sale.png" alt="" class="icon"/> 	
        <a href="#" class="small-box-footer">More info -></a>
	</div>
    <div class="small-box bg-purple">
        <div class="inner">
            <h3>150</h3>
            <p>Shipping</p>
        </div>
        <img src="images/shipping.png" alt="" class="icon"/> 	
        <a href="#" class="small-box-footer">More info -></a>
	</div>
    <div class="small-box bg-red">
        <div class="inner">
            <h3>150</h3>
            <p>Discount</p>
        </div>
        <img src="images/discount.png" alt="" class="icon"/> 	
        <a href="#" class="small-box-footer">More info -></a>
	</div>
