<div class="gray-line">
<div class="logo">
  <a href="#">
    <img src="images/logo.png" alt="The Mobile Market">
  </a>
  <a href="#"><strong>The Mobile Market</strong>

  </a>
  <br>Mobiles &amp; Accessories Store</div>
<nav>
  <ul>
    <li>
      <a href="?home" class="<?php  if(get_current_page_name() == "home")echo "current-page"?>">Home </a>
    </li>
    <li>
      <a href="?apple" class="<?php if(get_current_page_name()== "apple") echo "current-page"?>">Apple</a>
    </li>
    <li>
      <a href="?samsung" class="<?php if(get_current_page_name()== "samsung") echo "current-page"?>">Samsung</a>
    </li>
    <li>
      <a href="?others" class="<?php if(get_current_page_name()== "others") echo "current-page"?>">Accessories</a>
    </li>
    <li>
      <a href="#" class="<?php if(get_current_page_name()== "info") echo "current-page"?>">Info</a>
      <ul>
        <li>
          <a href="?feedback" class="<?php if(get_current_page_name()== "feedback") echo "current-page"?>">Feedback</a>
        </li>
        <li>
          <a href="#" class="<?php if(get_current_page_name()== "location") echo "current-page"?>">Location</a>
        </li>
      </ul>
    </li>
  </ul>
</nav>
</div>